### ISSUE TITLE
Transposition value mismatch?

### ISSUE THREAD

**Issue by m-r-m-s** [p3r7/argen#1]
Hey @p3r7,
I am noticing different transposition behavior when using K1 + E2 to transpose sample versus parameters>edit>Transpose
When using K1 + E2 transposition works as expected. For example: 0 ST down to -1, -2, etc and then back to 0 ST you get the default pitch.

When using parameters>edit>Transpose when you initially go down a semitone, say -1 and then go back to 0, it pitches it higher than the expected default pitch, even if the other transpose value on main GUI shows same value. Any value on parameters>edit>Transpose after you make a transposition will not reset back to default pitch with out restarting the script again.

You can hopefully reproduce by starting the script and generating any random pattern, then navigate to parameters>edit>Transpose and transpose the value. Changing up or down will not return you to the default pitch of the sample.
Perhaps this is related to Timber engine? I am not sure exactly how to determine or debug. For now the remedy is not to adjust the Transposition from the parameters>edit>Transpose side...

**Comment by p3r7** [comment]
hey!

thanks for reporting.

i'll try to look into it by the end of the week.

**Comment by m-r-m-s** [comment]
Great - thanks so much!

**Comment by p3r7** [comment]
hey!

fixed by https://github.com/p3r7/argen/commit/9ba37c1225cd363233414c5290cef5a6a54745c1.

thanks again fro reporting!
